apiVersion: artifactory.jfrog.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: artifactory-creds
      namespace: crossplane-system
      key: credentials
